<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-02-10">

<title>Results – MetabolismGraph</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7d6694c7b3d8f5ecf9ec986835a4b683.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MetabolismGraph</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./model.html"> 
<span class="menu-text">Model</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./gnn-llm-memory.html"> 
<span class="menu-text">GNN-LLM-Memory</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./results.html" aria-current="page"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./application.html"> 
<span class="menu-text">Application</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./references.html"> 
<span class="menu-text">References</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/allierc/MetabolismGraph" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#rate-constant-recovery-oscillatory-regime-rank-50" id="toc-rate-constant-recovery-oscillatory-regime-rank-50" class="nav-link active" data-scroll-target="#rate-constant-recovery-oscillatory-regime-rank-50">Rate Constant Recovery — Oscillatory Regime (rank 50)</a>
  <ul class="collapse">
  <li><a href="#simulation-setup" id="toc-simulation-setup" class="nav-link" data-scroll-target="#simulation-setup">Simulation Setup</a></li>
  <li><a href="#metrics" id="toc-metrics" class="nav-link" data-scroll-target="#metrics">Metrics</a></li>
  <li><a href="#r²-trajectory-across-136-iterations" id="toc-r²-trajectory-across-136-iterations" class="nav-link" data-scroll-target="#r²-trajectory-across-136-iterations">R² Trajectory Across 136 Iterations</a></li>
  <li><a href="#block-1-initial-exploration-iter-112" id="toc-block-1-initial-exploration-iter-112" class="nav-link" data-scroll-target="#block-1-initial-exploration-iter-112">Block 1: Initial Exploration (Iter 1–12)</a></li>
  <li><a href="#block-2-k_floor-breakthrough-iter-1324" id="toc-block-2-k_floor-breakthrough-iter-1324" class="nav-link" data-scroll-target="#block-2-k_floor-breakthrough-iter-1324">Block 2: k_floor Breakthrough (Iter 13–24)</a></li>
  <li><a href="#rate-constants-recovery" id="toc-rate-constants-recovery" class="nav-link" data-scroll-target="#rate-constants-recovery">Rate Constants Recovery</a></li>
  <li><a href="#kinograph" id="toc-kinograph" class="nav-link" data-scroll-target="#kinograph">Kinograph</a></li>
  <li><a href="#learned-mlps" id="toc-learned-mlps" class="nav-link" data-scroll-target="#learned-mlps">Learned MLPs</a></li>
  <li><a href="#block-3-plateau-and-breakthrough-iter-2536" id="toc-block-3-plateau-and-breakthrough-iter-2536" class="nav-link" data-scroll-target="#block-3-plateau-and-breakthrough-iter-2536">Block 3: Plateau and Breakthrough (Iter 25–36)</a></li>
  <li><a href="#block-4-seed-sensitivity-then-sub_diff7-breakthrough-iter-3748" id="toc-block-4-seed-sensitivity-then-sub_diff7-breakthrough-iter-3748" class="nav-link" data-scroll-target="#block-4-seed-sensitivity-then-sub_diff7-breakthrough-iter-3748">Block 4: Seed Sensitivity, then sub_diff=7 Breakthrough (Iter 37–48)</a></li>
  <li><a href="#block-5-confirming-tight-optimization-bounds-iter-4960" id="toc-block-5-confirming-tight-optimization-bounds-iter-4960" class="nav-link" data-scroll-target="#block-5-confirming-tight-optimization-bounds-iter-4960">Block 5: Confirming Tight Optimization Bounds (Iter 49–60)</a></li>
  <li><a href="#block-6-high-variance-discovery-iter-6172" id="toc-block-6-high-variance-discovery-iter-6172" class="nav-link" data-scroll-target="#block-6-high-variance-discovery-iter-6172">Block 6: High Variance Discovery (Iter 61–72)</a></li>
  <li><a href="#block-7-seed77-breakthrough-iter-7384" id="toc-block-7-seed77-breakthrough-iter-7384" class="nav-link" data-scroll-target="#block-7-seed77-breakthrough-iter-7384">Block 7: seed=77 Breakthrough (Iter 73–84)</a></li>
  <li><a href="#block-8-seed79-breakthrough-aug5000-iter-8596" id="toc-block-8-seed79-breakthrough-aug5000-iter-8596" class="nav-link" data-scroll-target="#block-8-seed79-breakthrough-aug5000-iter-8596">Block 8: seed=79 Breakthrough + aug=5000 (Iter 85–96)</a></li>
  <li><a href="#block-9-seed77sub_diff6-discovery-iter-97108" id="toc-block-9-seed77sub_diff6-discovery-iter-97108" class="nav-link" data-scroll-target="#block-9-seed77sub_diff6-discovery-iter-97108">Block 9: seed=77+sub_diff=6 Discovery (Iter 97–108)</a></li>
  <li><a href="#block-10-global-best-r²0.869-iter-109120" id="toc-block-10-global-best-r²0.869-iter-109120" class="nav-link" data-scroll-target="#block-10-global-best-r²0.869-iter-109120">Block 10: Global Best R²=0.869 (Iter 109–120)</a></li>
  <li><a href="#block-11-robustness-testing-iter-121132" id="toc-block-11-robustness-testing-iter-121132" class="nav-link" data-scroll-target="#block-11-robustness-testing-iter-121132">Block 11: Robustness Testing (Iter 121–132)</a></li>
  <li><a href="#block-12-k_floor1.5-variance-confirmed-iter-133136" id="toc-block-12-k_floor1.5-variance-confirmed-iter-133136" class="nav-link" data-scroll-target="#block-12-k_floor1.5-variance-confirmed-iter-133136">Block 12: k_floor=1.5 Variance Confirmed (Iter 133–136)</a></li>
  <li><a href="#ucb-exploration-tree" id="toc-ucb-exploration-tree" class="nav-link" data-scroll-target="#ucb-exploration-tree">UCB Exploration Tree</a></li>
  <li><a href="#established-principles" id="toc-established-principles" class="nav-link" data-scroll-target="#established-principles">Established Principles</a></li>
  <li><a href="#refuted-hypotheses" id="toc-refuted-hypotheses" class="nav-link" data-scroll-target="#refuted-hypotheses">Refuted Hypotheses</a></li>
  <li><a href="#open-questions" id="toc-open-questions" class="nav-link" data-scroll-target="#open-questions">Open Questions</a></li>
  </ul></li>
  <li><a href="#why-homeostasis-is-not-learned" id="toc-why-homeostasis-is-not-learned" class="nav-link" data-scroll-target="#why-homeostasis-is-not-learned">Why Homeostasis Is Not Learned</a>
  <ul class="collapse">
  <li><a href="#the-scale-mismatch-problem" id="toc-the-scale-mismatch-problem" class="nav-link" data-scroll-target="#the-scale-mismatch-problem">The scale mismatch problem</a></li>
  <li><a href="#homeostasis-is-an-integral-problem" id="toc-homeostasis-is-an-integral-problem" class="nav-link" data-scroll-target="#homeostasis-is-an-integral-problem">Homeostasis is an integral problem</a></li>
  <li><a href="#proposed-approach-two-phase-training" id="toc-proposed-approach-two-phase-training" class="nav-link" data-scroll-target="#proposed-approach-two-phase-training">Proposed approach: two-phase training</a></li>
  <li><a href="#alternative-approach-residual-based-supervision" id="toc-alternative-approach-residual-based-supervision" class="nav-link" data-scroll-target="#alternative-approach-residual-based-supervision">Alternative approach: residual-based supervision</a></li>
  <li><a href="#direct-evidence-the-one-step-derivative-residual-is-the-homeostasis-signal" id="toc-direct-evidence-the-one-step-derivative-residual-is-the-homeostasis-signal" class="nav-link" data-scroll-target="#direct-evidence-the-one-step-derivative-residual-is-the-homeostasis-signal">Direct evidence: the one-step derivative residual is the homeostasis signal</a></li>
  <li><a href="#related-work" id="toc-related-work" class="nav-link" data-scroll-target="#related-work">Related work</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Results</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button" data-quarto-source-url="https://github.com/allierc/MetabolismGraph/blob/main/results.qmd">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="rate-constant-recovery-oscillatory-regime-rank-50" class="level2">
<h2 class="anchored" data-anchor-id="rate-constant-recovery-oscillatory-regime-rank-50">Rate Constant Recovery — Oscillatory Regime (rank 50)</h2>
<p>The LLM-driven exploration engine is running on the <strong>oscillatory regime</strong> (activity rank <span class="math inline">\(\sim50\)</span>): 100 metabolites, 256 autocatalytic reactions, 2880 time frames, mass-action kinetics with the stoichiometric matrix <span class="math inline">\(\mathbf{S}\)</span> frozen from ground truth. The goal is to recover the 256 rate constants <span class="math inline">\(k_j \in [10^{-2}, 10^{-1}]\)</span> by optimizing training hyperparameters through UCB tree search with 4 parallel slots.</p>
<p><strong>136 iterations completed</strong> across 12 blocks (34 batches). The exploration is ongoing.</p>
<section id="simulation-setup" class="level3">
<h3 class="anchored" data-anchor-id="simulation-setup">Simulation Setup</h3>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-concentrations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-concentrations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/concentrations.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Concentration dynamics of 100 metabolites over 2880 time frames. Activity rank = 47 — most reactions actively contribute to the dynamics."><img src="figures/rank_50/concentrations.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-concentrations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Concentration dynamics of 100 metabolites over 2880 time frames. Activity rank = 47 — most reactions actively contribute to the dynamics.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-stoichiometry" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stoichiometry-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/stoichiometry.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: Stoichiometric matrix \mathbf{S} (100 metabolites \times 256 reactions). Red = products (+1), blue = substrates (–1). 100% autocatalytic 3-cycles."><img src="figures/rank_50/stoichiometry.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stoichiometry-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Stoichiometric matrix <span class="math inline">\(\mathbf{S}\)</span> (100 metabolites <span class="math inline">\(\times\)</span> 256 reactions). Red = products (+1), blue = substrates (–1). 100% autocatalytic 3-cycles.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="metrics" class="level3">
<h3 class="anchored" data-anchor-id="metrics">Metrics</h3>
<p>The primary metric is <strong>raw R²</strong> computed on all 256 reactions (after MLP<span class="math inline">\(_{\text{sub}}\)</span> scalar correction). The <strong>trimmed R²</strong> excludes outlier reactions (<span class="math inline">\(|\Delta \log_{10} k| &gt; 0.3\)</span>) and is reported in parentheses. Raw R² is what drives the UCB exploration — it penalizes outliers directly instead of hiding them.</p>
</section>
<section id="r²-trajectory-across-136-iterations" class="level3">
<h3 class="anchored" data-anchor-id="r²-trajectory-across-136-iterations">R² Trajectory Across 136 Iterations</h3>
<div id="cell-fig-iterations" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>iters <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">137</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> [</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 1 (Iter 1-12): Initial exploration</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.044</span>, <span class="fl">0.027</span>, <span class="fl">0.044</span>, <span class="fl">0.031</span>,  <span class="co"># Batch 1: initial sweep</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.013</span>, <span class="fl">0.067</span>, <span class="fl">0.041</span>, <span class="fl">0.051</span>,  <span class="co"># Batch 2: sub_norm breakthrough</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.054</span>, <span class="fl">0.061</span>, <span class="fl">0.017</span>, <span class="fl">0.061</span>,  <span class="co"># Batch 3: MLP_node activation</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 2 (Iter 13-24): k_floor breakthrough</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.056</span>, <span class="fl">0.508</span>, <span class="fl">0.011</span>, <span class="fl">0.057</span>,  <span class="co"># Batch 4: k_floor=1.0 breakthrough</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.638</span>, <span class="fl">0.642</span>, <span class="fl">0.470</span>, <span class="fl">0.373</span>,  <span class="co"># Batch 5: exploiting k_floor</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.690</span>, <span class="fl">0.419</span>, <span class="fl">0.658</span>, <span class="fl">0.559</span>,  <span class="co"># Batch 6: aug=4000 best</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 3 (Iter 25-36): Plateau then lr_sub breakthrough</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.652</span>, <span class="fl">0.638</span>, <span class="fl">0.614</span>, <span class="fl">0.600</span>,  <span class="co"># Batch 7: diminishing returns</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.507</span>, <span class="fl">0.619</span>, <span class="fl">0.530</span>, <span class="fl">0.409</span>,  <span class="co"># Batch 8: alternative approaches</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.521</span>, <span class="fl">0.478</span>, <span class="fl">0.726</span>, <span class="fl">0.544</span>,  <span class="co"># Batch 9: lr_sub=0.001 BREAKTHROUGH</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 4 (Iter 37-48): Seed sensitivity then sub_diff=7</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.588</span>, <span class="fl">0.518</span>, <span class="fl">0.654</span>, <span class="fl">0.662</span>,  <span class="co"># Batch 10: combinations with lr_sub</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.487</span>, <span class="fl">0.690</span>, <span class="fl">0.608</span>, <span class="fl">0.593</span>,  <span class="co"># Batch 11: seed sensitivity revealed</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.736</span>, <span class="fl">0.483</span>, <span class="fl">0.559</span>, <span class="fl">0.556</span>,  <span class="co"># Batch 12: sub_diff=7 NEW BEST</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 5 (Iter 49-60): Confirming optimum</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.696</span>, <span class="fl">0.591</span>, <span class="fl">0.655</span>, <span class="fl">0.545</span>,  <span class="co"># Batch 13: robustness tests</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.662</span>, <span class="fl">0.560</span>, <span class="fl">0.701</span>, <span class="fl">0.600</span>,  <span class="co"># Batch 14: fine-tuning bounds</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.701</span>, <span class="fl">0.718</span>, <span class="fl">0.603</span>, <span class="fl">0.603</span>,  <span class="co"># Batch 15: seed=99 promising</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 6 (Iter 61-72): Variance discovery</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.688</span>, <span class="fl">0.430</span>, <span class="fl">0.616</span>, <span class="fl">0.704</span>,  <span class="co"># Batch 16: k_floor=1.5 promising</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.565</span>, <span class="fl">0.674</span>, <span class="fl">0.664</span>, <span class="fl">0.609</span>,  <span class="co"># Batch 17: k_floor non-monotonic</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.658</span>, <span class="fl">0.639</span>, <span class="fl">0.473</span>, <span class="fl">0.550</span>,  <span class="co"># Batch 18: HIGH VARIANCE discovered</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 7 (Iter 73-84): seed=77 breakthrough</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.722</span>, <span class="fl">0.583</span>, <span class="fl">0.682</span>, <span class="fl">0.636</span>,  <span class="co"># Batch 19: seed=123 improved</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.694</span>, <span class="fl">0.515</span>, <span class="fl">0.473</span>, <span class="fl">0.748</span>,  <span class="co"># Batch 20: seed=77 NEW BEST</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.661</span>, <span class="fl">0.764</span>, <span class="fl">0.387</span>, <span class="fl">0.689</span>,  <span class="co"># Batch 21: seed=77+sub_diff=8 PEAK</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 8 (Iter 85-96): seed=79 breakthrough + aug=5000</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.619</span>, <span class="fl">0.512</span>, <span class="fl">0.748</span>, <span class="fl">0.720</span>,  <span class="co"># Batch 22: seed=79 golden seed discovered</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.822</span>, <span class="fl">0.640</span>, <span class="fl">0.572</span>, <span class="fl">0.704</span>,  <span class="co"># Batch 23: seed=79 replicate R²=0.82</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.592</span>, <span class="fl">0.619</span>, <span class="fl">0.546</span>, <span class="fl">0.851</span>,  <span class="co"># Batch 24: seed=79+aug=5000 NEW BEST</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 9 (Iter 97-108): seed=77+sub_diff=6 discovery</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.720</span>, <span class="fl">0.609</span>, <span class="fl">0.742</span>, <span class="fl">0.471</span>,  <span class="co"># Batch 25: aug=5500 hurts seed=79</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.754</span>, <span class="fl">0.634</span>, <span class="fl">0.730</span>, <span class="fl">0.764</span>,  <span class="co"># Batch 26: sub_diff=7 for seed=77</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.780</span>, <span class="fl">0.804</span>, <span class="fl">0.683</span>, <span class="fl">0.623</span>,  <span class="co"># Batch 27: sub_diff=6 2ND BEST</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 10 (Iter 109-120): GLOBAL BEST iter 116</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.550</span>, <span class="fl">0.572</span>, <span class="fl">0.655</span>, <span class="fl">0.589</span>,  <span class="co"># Batch 28: sub_diff=6 cross-seed (variance!)</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.637</span>, <span class="fl">0.643</span>, <span class="fl">0.566</span>, <span class="fl">0.869</span>,  <span class="co"># Batch 29: seed=77+sub_diff=6+aug=5500 GLOBAL BEST</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.657</span>, <span class="fl">0.518</span>, <span class="fl">0.581</span>, <span class="fl">0.812</span>,  <span class="co"># Batch 30: aug=5750 hurts, sub_diff=7 good</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 11 (Iter 121-132): Robustness testing</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.734</span>, <span class="fl">0.733</span>, <span class="fl">0.574</span>, <span class="fl">0.509</span>,  <span class="co"># Batch 31: sub_diff=7 robust, sub_diff=8 hurts</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.782</span>, <span class="fl">0.680</span>, <span class="fl">0.544</span>, <span class="fl">0.670</span>,  <span class="co"># Batch 32: sub_diff=7 variance ~0.05</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.509</span>, <span class="fl">0.675</span>, <span class="fl">0.721</span>, <span class="fl">0.846</span>,  <span class="co"># Batch 33: k_floor=1.5 2ND BEST</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Block 12 (Iter 133-136): k_floor=1.5 variance confirmed</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>    <span class="fl">0.635</span>, <span class="fl">0.512</span>, <span class="fl">0.677</span>, <span class="fl">0.692</span>,  <span class="co"># Batch 34: k_floor=1.5 not reproducible</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>outliers <span class="op">=</span> [</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>    <span class="dv">43</span>, <span class="dv">47</span>, <span class="dv">45</span>, <span class="dv">53</span>,</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>    <span class="dv">61</span>, <span class="dv">36</span>, <span class="dv">45</span>, <span class="dv">32</span>,</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>    <span class="dv">27</span>, <span class="dv">38</span>, <span class="dv">57</span>, <span class="dv">30</span>,</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>    <span class="dv">28</span>, <span class="dv">33</span>, <span class="dv">36</span>, <span class="dv">33</span>,</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>    <span class="dv">17</span>, <span class="dv">24</span>, <span class="dv">26</span>, <span class="dv">35</span>,</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>    <span class="dv">16</span>, <span class="dv">29</span>, <span class="dv">19</span>, <span class="dv">24</span>,</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>    <span class="dv">18</span>, <span class="dv">18</span>, <span class="dv">15</span>, <span class="dv">17</span>,</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>    <span class="dv">19</span>, <span class="dv">14</span>, <span class="dv">21</span>, <span class="dv">21</span>,</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>    <span class="dv">21</span>, <span class="dv">21</span>, <span class="dv">15</span>, <span class="dv">22</span>,  <span class="co"># Batch 9</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>    <span class="dv">16</span>, <span class="dv">19</span>, <span class="dv">20</span>, <span class="dv">21</span>,  <span class="co"># Batch 10</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>    <span class="dv">21</span>, <span class="dv">16</span>, <span class="dv">18</span>, <span class="dv">19</span>,  <span class="co"># Batch 11</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>    <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">23</span>, <span class="dv">21</span>,  <span class="co"># Batch 12</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>    <span class="dv">12</span>, <span class="dv">21</span>, <span class="dv">12</span>, <span class="dv">25</span>,  <span class="co"># Batch 13</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>    <span class="dv">21</span>, <span class="dv">21</span>, <span class="dv">18</span>, <span class="dv">19</span>,  <span class="co"># Batch 14</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>    <span class="dv">17</span>, <span class="dv">17</span>, <span class="dv">16</span>, <span class="dv">20</span>,  <span class="co"># Batch 15</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>    <span class="dv">17</span>, <span class="dv">20</span>, <span class="dv">17</span>, <span class="dv">16</span>,  <span class="co"># Batch 16</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>    <span class="dv">17</span>, <span class="dv">14</span>, <span class="dv">16</span>, <span class="dv">14</span>,  <span class="co"># Batch 17</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>    <span class="dv">19</span>, <span class="dv">14</span>, <span class="dv">22</span>, <span class="dv">17</span>,  <span class="co"># Batch 18</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>    <span class="dv">19</span>, <span class="dv">16</span>, <span class="dv">22</span>, <span class="dv">20</span>,  <span class="co"># Batch 19</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>    <span class="dv">16</span>, <span class="dv">16</span>, <span class="dv">32</span>, <span class="dv">12</span>,  <span class="co"># Batch 20</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>    <span class="dv">16</span>, <span class="dv">15</span>, <span class="dv">23</span>, <span class="dv">18</span>,  <span class="co"># Batch 21</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>    <span class="dv">16</span>, <span class="dv">22</span>, <span class="dv">15</span>, <span class="dv">20</span>,  <span class="co"># Batch 22</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>    <span class="dv">13</span>, <span class="dv">13</span>, <span class="dv">15</span>, <span class="dv">17</span>,  <span class="co"># Batch 23</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>    <span class="dv">22</span>, <span class="dv">14</span>, <span class="dv">21</span>, <span class="dv">11</span>,  <span class="co"># Batch 24</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>    <span class="dv">18</span>, <span class="dv">20</span>, <span class="dv">15</span>, <span class="dv">16</span>,  <span class="co"># Batch 25</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>    <span class="dv">17</span>, <span class="dv">16</span>, <span class="dv">16</span>, <span class="dv">13</span>,  <span class="co"># Batch 26</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>    <span class="dv">16</span>, <span class="dv">12</span>, <span class="dv">14</span>, <span class="dv">12</span>,  <span class="co"># Batch 27</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>    <span class="dv">14</span>, <span class="dv">15</span>, <span class="dv">18</span>, <span class="dv">17</span>,  <span class="co"># Batch 28</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>    <span class="dv">15</span>, <span class="dv">17</span>, <span class="dv">17</span>, <span class="dv">10</span>,  <span class="co"># Batch 29</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>    <span class="dv">18</span>, <span class="dv">20</span>, <span class="dv">15</span>, <span class="dv">10</span>,  <span class="co"># Batch 30</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>    <span class="dv">12</span>, <span class="dv">10</span>, <span class="dv">17</span>, <span class="dv">14</span>,  <span class="co"># Batch 31</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>    <span class="dv">10</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">14</span>,  <span class="co"># Batch 32</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>    <span class="dv">18</span>, <span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">12</span>,  <span class="co"># Batch 33</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>    <span class="dv">18</span>, <span class="dv">21</span>, <span class="dv">11</span>, <span class="dv">20</span>,  <span class="co"># Batch 34</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="co"># Color by block</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>block_colors <span class="op">=</span> [</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>    <span class="st">'#3498db'</span>, <span class="st">'#2ecc71'</span>, <span class="st">'#e67e22'</span>, <span class="st">'#9b59b6'</span>,</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>    <span class="st">'#1abc9c'</span>, <span class="st">'#e84393'</span>, <span class="st">'#f39c12'</span>, <span class="st">'#e74c3c'</span>,</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>    <span class="st">'#2c3e50'</span>, <span class="st">'#d35400'</span>, <span class="st">'#8e44ad'</span>, <span class="st">'#27ae60'</span>,</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>block_bounds <span class="op">=</span> [<span class="dv">12</span>, <span class="dv">24</span>, <span class="dv">36</span>, <span class="dv">48</span>, <span class="dv">60</span>, <span class="dv">72</span>, <span class="dv">84</span>, <span class="dv">96</span>, <span class="dv">108</span>, <span class="dv">120</span>, <span class="dv">132</span>, <span class="dv">136</span>]</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> []</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(r2)):</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> b, bound <span class="kw">in</span> <span class="bu">enumerate</span>(block_bounds):</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> i <span class="op">&lt;</span> bound:</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>            colors.append(block_colors[b])</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>fig, ax1 <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">18</span>, <span class="dv">5</span>))</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax1.bar(iters, r2, color<span class="op">=</span>colors, edgecolor<span class="op">=</span><span class="st">'white'</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>, alpha<span class="op">=</span><span class="fl">0.85</span>)</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>ax1.axhline(y<span class="op">=</span><span class="fl">0.869</span>, color<span class="op">=</span><span class="st">'#e74c3c'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.4</span>, label<span class="op">=</span><span class="st">'Peak R² = 0.869'</span>)</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>ax1.axhline(y<span class="op">=</span><span class="fl">0.690</span>, color<span class="op">=</span><span class="st">'#2ecc71'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, label<span class="op">=</span><span class="st">'Stable R² ≈ 0.69'</span>)</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="co"># Block separators and labels</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> b <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(block_bounds) <span class="op">-</span> <span class="dv">1</span>):</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>    ax1.axvline(x<span class="op">=</span>block_bounds[b] <span class="op">+</span> <span class="fl">0.5</span>, color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, alpha<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>block_labels <span class="op">=</span> [</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Block 1'</span>, <span class="st">'Block 2'</span>, <span class="st">'Block 3'</span>, <span class="st">'Block 4'</span>, <span class="st">'Block 5'</span>, <span class="st">'Block 6'</span>,</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Block 7'</span>, <span class="st">'Block 8'</span>, <span class="st">'Block 9'</span>, <span class="st">'Block 10'</span>, <span class="st">'Block 11'</span>, <span class="st">'Block 12'</span>,</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>block_centers <span class="op">=</span> [<span class="fl">6.5</span>, <span class="fl">18.5</span>, <span class="fl">30.5</span>, <span class="fl">42.5</span>, <span class="fl">54.5</span>, <span class="fl">66.5</span>, <span class="fl">78.5</span>, <span class="fl">90.5</span>, <span class="fl">102.5</span>, <span class="fl">114.5</span>, <span class="fl">126.5</span>, <span class="fl">134.5</span>]</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (lbl, cx) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">zip</span>(block_labels, block_centers)):</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>    ax1.text(cx, <span class="fl">1.05</span>, lbl, ha<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">7</span>, color<span class="op">=</span>block_colors[i],</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>             bbox<span class="op">=</span><span class="bu">dict</span>(boxstyle<span class="op">=</span><span class="st">'round,pad=0.2'</span>, facecolor<span class="op">=</span><span class="st">'white'</span>, edgecolor<span class="op">=</span><span class="st">'none'</span>, alpha<span class="op">=</span><span class="fl">0.8</span>))</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="co"># Annotate key events</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">'k_floor=1.0</span><span class="ch">\n</span><span class="st">breakthrough'</span>, xy<span class="op">=</span>(<span class="dv">14</span>, <span class="fl">0.508</span>), xytext<span class="op">=</span>(<span class="dv">14</span>, <span class="fl">0.25</span>),</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, color<span class="op">=</span><span class="st">'black'</span>), fontsize<span class="op">=</span><span class="dv">7</span>, ha<span class="op">=</span><span class="st">'center'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">'aug=4000'</span>, xy<span class="op">=</span>(<span class="dv">21</span>, <span class="fl">0.690</span>), xytext<span class="op">=</span>(<span class="dv">21</span>, <span class="fl">0.82</span>),</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, color<span class="op">=</span><span class="st">'black'</span>), fontsize<span class="op">=</span><span class="dv">7</span>, ha<span class="op">=</span><span class="st">'center'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">'lr_sub=0.001'</span>, xy<span class="op">=</span>(<span class="dv">35</span>, <span class="fl">0.726</span>), xytext<span class="op">=</span>(<span class="dv">33</span>, <span class="fl">0.86</span>),</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, color<span class="op">=</span><span class="st">'black'</span>), fontsize<span class="op">=</span><span class="dv">7</span>, ha<span class="op">=</span><span class="st">'center'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">'sub_diff=7'</span>, xy<span class="op">=</span>(<span class="dv">45</span>, <span class="fl">0.736</span>), xytext<span class="op">=</span>(<span class="dv">45</span>, <span class="fl">0.86</span>),</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, color<span class="op">=</span><span class="st">'black'</span>), fontsize<span class="op">=</span><span class="dv">7</span>, ha<span class="op">=</span><span class="st">'center'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">'seed=77+</span><span class="ch">\n</span><span class="st">sub_diff=8'</span>, xy<span class="op">=</span>(<span class="dv">82</span>, <span class="fl">0.764</span>), xytext<span class="op">=</span>(<span class="dv">82</span>, <span class="fl">0.90</span>),</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, color<span class="op">=</span><span class="st">'black'</span>), fontsize<span class="op">=</span><span class="dv">7</span>, ha<span class="op">=</span><span class="st">'center'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">'seed=79+</span><span class="ch">\n</span><span class="st">aug=5000'</span>, xy<span class="op">=</span>(<span class="dv">96</span>, <span class="fl">0.851</span>), xytext<span class="op">=</span>(<span class="dv">93</span>, <span class="fl">0.95</span>),</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, color<span class="op">=</span><span class="st">'black'</span>), fontsize<span class="op">=</span><span class="dv">7</span>, ha<span class="op">=</span><span class="st">'center'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">'sub_diff=6</span><span class="ch">\n</span><span class="st">R²=0.80'</span>, xy<span class="op">=</span>(<span class="dv">106</span>, <span class="fl">0.804</span>), xytext<span class="op">=</span>(<span class="dv">106</span>, <span class="fl">0.90</span>),</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, color<span class="op">=</span><span class="st">'black'</span>), fontsize<span class="op">=</span><span class="dv">7</span>, ha<span class="op">=</span><span class="st">'center'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">'GLOBAL BEST</span><span class="ch">\n</span><span class="st">R²=0.87'</span>, xy<span class="op">=</span>(<span class="dv">116</span>, <span class="fl">0.869</span>), xytext<span class="op">=</span>(<span class="dv">116</span>, <span class="fl">0.96</span>),</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, color<span class="op">=</span><span class="st">'red'</span>), fontsize<span class="op">=</span><span class="dv">7</span>, ha<span class="op">=</span><span class="st">'center'</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">'k_floor=1.5</span><span class="ch">\n</span><span class="st">R²=0.85'</span>, xy<span class="op">=</span>(<span class="dv">132</span>, <span class="fl">0.846</span>), xytext<span class="op">=</span>(<span class="dv">132</span>, <span class="fl">0.93</span>),</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'-&gt;'</span>, color<span class="op">=</span><span class="st">'black'</span>), fontsize<span class="op">=</span><span class="dv">7</span>, ha<span class="op">=</span><span class="st">'center'</span>, color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">'Iteration'</span>)</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'rate_constants R² (raw)'</span>)</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>ax1.set_ylim(<span class="op">-</span><span class="fl">0.02</span>, <span class="fl">1.05</span>)</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>ax1.set_xticks([<span class="dv">1</span>, <span class="dv">12</span>, <span class="dv">24</span>, <span class="dv">36</span>, <span class="dv">48</span>, <span class="dv">60</span>, <span class="dv">72</span>, <span class="dv">84</span>, <span class="dv">96</span>, <span class="dv">106</span>, <span class="dv">108</span>, <span class="dv">116</span>, <span class="dv">120</span>, <span class="dv">132</span>, <span class="dv">136</span>])</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="co"># outlier count on secondary axis</span></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> ax1.twinx()</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>ax2.plot(iters, outliers, <span class="st">'o'</span>, color<span class="op">=</span><span class="st">'black'</span>, markersize<span class="op">=</span><span class="dv">3</span>, alpha<span class="op">=</span><span class="fl">0.4</span>, label<span class="op">=</span><span class="st">'outliers'</span>)</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'outlier count'</span>)</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>ax2.tick_params(axis<span class="op">=</span><span class="st">'y'</span>)</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>ax2.set_ylim(<span class="dv">0</span>, <span class="dv">70</span>)</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>lines1, labels1 <span class="op">=</span> ax1.get_legend_handles_labels()</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>lines2, labels2 <span class="op">=</span> ax2.get_legend_handles_labels()</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>ax1.legend(lines1 <span class="op">+</span> lines2, labels1 <span class="op">+</span> labels2, loc<span class="op">=</span><span class="st">'upper left'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'UCB Exploration: Rate Constant Recovery (136 iterations)'</span>)</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-iterations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-iterations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="results_files/figure-html/fig-iterations-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;3: Raw R² (bars) and outlier count (dots) across 136 iterations, colored by block. Key breakthroughs: k_floor (iter 14, 0.07→0.51), aug=4000 (iter 21, 0.69), lr_sub=0.001 (iter 35, 0.73), sub_diff=7 (iter 45, 0.74), seed=77+sub_diff=8 (iter 82, 0.76), seed=79+aug=5000 (iter 96, 0.85), seed=77+sub_diff=6 (iter 106, 0.80), seed=77+sub_diff=6+aug=5500 (iter 116, 0.87). Training variance of ±0.2 R² is a dominant factor."><img src="results_files/figure-html/fig-iterations-output-1.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iterations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Raw R² (bars) and outlier count (dots) across 136 iterations, colored by block. Key breakthroughs: k_floor (iter 14, 0.07→0.51), aug=4000 (iter 21, 0.69), lr_sub=0.001 (iter 35, 0.73), sub_diff=7 (iter 45, 0.74), seed=77+sub_diff=8 (iter 82, 0.76), seed=79+aug=5000 (iter 96, 0.85), seed=77+sub_diff=6 (iter 106, 0.80), seed=77+sub_diff=6+aug=5500 (iter 116, 0.87). Training variance of ±0.2 R² is a dominant factor.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="block-1-initial-exploration-iter-112" class="level3">
<h3 class="anchored" data-anchor-id="block-1-initial-exploration-iter-112">Block 1: Initial Exploration (Iter 1–12)</h3>
<p>All 12 iterations achieved raw R² &lt; 0.07. The key discovery was that <code>coeff_MLP_sub_norm=1.0</code> is essential — it corrects the MLP<span class="math inline">\(_{\text{sub}}\)</span> function shapes (c² becomes quadratic instead of linear) and enables MLP<span class="math inline">\(_{\text{node}}\)</span> to learn homeostasis.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 (iter 1–4)</td>
<td>lr sweep</td>
<td>0.044</td>
<td>All failed; MLP<span class="math inline">\(_{\text{node}}\)</span> dead, MLP<span class="math inline">\(_{\text{sub}}\)</span> c² linear</td>
</tr>
<tr class="even">
<td>2 (iter 5–8)</td>
<td><code>sub_norm=1.0</code></td>
<td><strong>0.067</strong></td>
<td>MLP<span class="math inline">\(_{\text{sub}}\)</span> normalization is the single most effective change</td>
</tr>
<tr class="odd">
<td>3 (iter 9–12)</td>
<td>combine best</td>
<td>0.061</td>
<td>MLP<span class="math inline">\(_{\text{node}}\)</span> activated; <code>lr_node=0.005</code> hurts</td>
</tr>
</tbody>
</table>
</section>
<section id="block-2-k_floor-breakthrough-iter-1324" class="level3">
<h3 class="anchored" data-anchor-id="block-2-k_floor-breakthrough-iter-1324">Block 2: k_floor Breakthrough (Iter 13–24)</h3>
<p>The <code>coeff_k_floor=1.0</code> penalty at iteration 14 produced a <strong>10× improvement</strong> in R² (0.06 → 0.51) by preventing outlier <span class="math inline">\(\log k\)</span> values from drifting below the true minimum. Longer training then pushed R² to 0.69.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4 (iter 13–16)</td>
<td><code>k_floor=1.0</code></td>
<td><strong>0.508</strong></td>
<td>Breakthrough — R² jumped 10×</td>
</tr>
<tr class="even">
<td>5 (iter 17–20)</td>
<td><code>aug=3000</code></td>
<td><strong>0.642</strong></td>
<td>Longer training + k_floor synergistic</td>
</tr>
<tr class="odd">
<td>6 (iter 21–24)</td>
<td><code>aug=4000</code></td>
<td><strong>0.690</strong></td>
<td>First to reach 0.69; <span class="math inline">\(\alpha = 0.85\)</span>, 16 outliers</td>
</tr>
</tbody>
</table>
<p><strong>Best result — Iteration 116</strong>: <code>seed=77</code>, <code>coeff_MLP_sub_diff=6</code>, <code>lr_sub=0.001</code>, <code>data_augmentation_loop=5500</code>, <code>coeff_k_floor=1.0</code>, <code>coeff_MLP_sub_norm=1.0</code></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raw R²</td>
<td><strong>0.869</strong></td>
</tr>
<tr class="even">
<td>Outliers</td>
<td>10 / 256 (3.9%)</td>
</tr>
<tr class="odd">
<td>Slope</td>
<td>0.98</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\alpha\)</span></td>
<td>0.93</td>
</tr>
</tbody>
</table>
<p><em>Note: Optimal <code>sub_diff</code> and <code>aug</code> are seed-dependent: <code>sub_diff=6</code> for seed=77 (R²=0.87), <code>sub_diff=7</code> for seed=42 (R²=0.74), <code>sub_diff=8</code> for seed=79 (R²=0.85). seed=77 benefits from <code>aug=5500</code>, seed=79 from <code>aug=5000</code>. Training has intrinsic variance of $$0.2–0.3 R² even with identical configuration.</em></p>
</section>
<section id="rate-constants-recovery" class="level3">
<h3 class="anchored" data-anchor-id="rate-constants-recovery">Rate Constants Recovery</h3>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-k-baseline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-k-baseline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/rate_constants_baseline.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;4: Iteration 1 (baseline). R² = 0.044, 43 outliers. Before k_floor and sub_norm — predicted \log k values scatter widely with no correlation to ground truth."><img src="figures/rank_50/rate_constants_baseline.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-k-baseline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Iteration 1 (baseline). R² = 0.044, 43 outliers. Before <code>k_floor</code> and <code>sub_norm</code> — predicted <span class="math inline">\(\log k\)</span> values scatter widely with no correlation to ground truth.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-k-breakthrough" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-k-breakthrough-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/rate_constants_breakthrough.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;5: Iteration 14 (breakthrough). R² = 0.508, 33 outliers. The k_floor=1.0 penalty prevents outlier \log k from drifting below the true minimum, producing a 10\times R² jump."><img src="figures/rank_50/rate_constants_breakthrough.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-k-breakthrough-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Iteration 14 (breakthrough). R² = 0.508, 33 outliers. The <code>k_floor=1.0</code> penalty prevents outlier <span class="math inline">\(\log k\)</span> from drifting below the true minimum, producing a 10<span class="math inline">\(\times\)</span> R² jump.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-k-best" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-k-best-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/rate_constants_best.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;6: Iteration 116 (best). R² = 0.869, 10 outliers. seed=77 + sub_diff=6 + aug=5500 yields the tightest clustering around the diagonal."><img src="figures/rank_50/rate_constants_best.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-k-best-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Iteration 116 (best). R² = 0.869, 10 outliers. <code>seed=77</code> + <code>sub_diff=6</code> + <code>aug=5500</code> yields the tightest clustering around the diagonal.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="kinograph" class="level3">
<h3 class="anchored" data-anchor-id="kinograph">Kinograph</h3>
<div id="fig-kinograph-baseline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kinograph-baseline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/kinograph_baseline.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;7: Iteration 1 (baseline). Top-left: ground-truth dc/dt; top-right: GNN prediction; bottom-left: residual; bottom-right: scatter. The untrained GNN produces near-zero predictions — no reaction dynamics captured."><img src="figures/rank_50/kinograph_baseline.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kinograph-baseline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Iteration 1 (baseline). Top-left: ground-truth <span class="math inline">\(dc/dt\)</span>; top-right: GNN prediction; bottom-left: residual; bottom-right: scatter. The untrained GNN produces near-zero predictions — no reaction dynamics captured.
</figcaption>
</figure>
</div>
<div id="fig-kinograph-best" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kinograph-best-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/kinograph_best.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;8: Iteration 116 (best, seed=77, sub_diff=6, aug=5500). Same layout. The GNN captures the dominant oscillatory patterns but misses fine-grained temporal structure. The residual reveals the missing homeostatic signal."><img src="figures/rank_50/kinograph_best.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kinograph-best-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Iteration 116 (best, seed=77, sub_diff=6, aug=5500). Same layout. The GNN captures the dominant oscillatory patterns but misses fine-grained temporal structure. The residual reveals the missing homeostatic signal.
</figcaption>
</figure>
</div>
</section>
<section id="learned-mlps" class="level3">
<h3 class="anchored" data-anchor-id="learned-mlps">Learned MLPs</h3>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlp-baseline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlp-baseline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/mlp_baseline.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;9: Iteration 1 (baseline). MLP_{\text{sub}}: \alpha at |s|=1 is 0.42 — under-scaled. MLP_{\text{node}}: flat at zero."><img src="figures/rank_50/mlp_baseline.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlp-baseline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Iteration 1 (baseline). MLP<span class="math inline">\(_{\text{sub}}\)</span>: <span class="math inline">\(\alpha\)</span> at <span class="math inline">\(|s|=1\)</span> is 0.42 — under-scaled. MLP<span class="math inline">\(_{\text{node}}\)</span>: flat at zero.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mlp-best" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mlp-best-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/mlp_best.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;10: Iteration 116 (best R²). MLP_{\text{sub}}: \alpha at |s|=1 is 0.93 — close to the true scale. MLP_{\text{node}}: still flat at zero across all 136 iterations — homeostasis not learned."><img src="figures/rank_50/mlp_best.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mlp-best-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Iteration 116 (best R²). MLP<span class="math inline">\(_{\text{sub}}\)</span>: <span class="math inline">\(\alpha\)</span> at <span class="math inline">\(|s|=1\)</span> is 0.93 — close to the true scale. MLP<span class="math inline">\(_{\text{node}}\)</span>: still flat at zero across all 136 iterations — homeostasis not learned.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="block-3-plateau-and-breakthrough-iter-2536" class="level3">
<h3 class="anchored" data-anchor-id="block-3-plateau-and-breakthrough-iter-2536">Block 3: Plateau and Breakthrough (Iter 25–36)</h3>
<p>Twelve iterations explored the R² = 0.69 plateau. Eight variations failed — but doubling <code>lr_sub</code> from 0.0005 to 0.001 broke through to R² = 0.726.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7 (iter 25–28)</td>
<td><code>aug=5000</code>, seed, batch_size</td>
<td>0.652</td>
<td><code>aug=5000</code> hurt R² but <span class="math inline">\(\alpha=0.95\)</span> (best ever)</td>
</tr>
<tr class="even">
<td>8 (iter 29–32)</td>
<td>L1=0, <code>sub_norm=2.0</code>, lr_k</td>
<td>0.619</td>
<td><code>sub_norm=2.0</code>: fewest outliers (14), best slope (0.99)</td>
</tr>
<tr class="odd">
<td>9 (iter 33–36)</td>
<td><code>sub_norm=2.0</code>+<code>aug=3500</code>, recurrent, <strong><code>lr_sub=0.001</code></strong>, <code>aug=3500</code></td>
<td><strong>0.726</strong></td>
<td><code>lr_sub=0.001</code> broke the plateau</td>
</tr>
</tbody>
</table>
<div id="cell-fig-strategies" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>strategies <span class="op">=</span> {</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'No k_floor</span><span class="ch">\n</span><span class="st">(Block 1)'</span>: [<span class="fl">0.044</span>, <span class="fl">0.027</span>, <span class="fl">0.044</span>, <span class="fl">0.031</span>, <span class="fl">0.013</span>, <span class="fl">0.067</span>, <span class="fl">0.041</span>, <span class="fl">0.051</span>, <span class="fl">0.054</span>, <span class="fl">0.061</span>, <span class="fl">0.017</span>, <span class="fl">0.061</span>],</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'k_floor</span><span class="ch">\n</span><span class="st">sub_diff=5</span><span class="ch">\n</span><span class="st">seed=42'</span>: [<span class="fl">0.508</span>, <span class="fl">0.638</span>, <span class="fl">0.419</span>, <span class="fl">0.658</span>, <span class="fl">0.559</span>, <span class="fl">0.470</span>, <span class="fl">0.373</span>, <span class="fl">0.690</span>, <span class="fl">0.652</span>, <span class="fl">0.638</span>, <span class="fl">0.614</span>, <span class="fl">0.600</span>, <span class="fl">0.507</span>, <span class="fl">0.619</span>, <span class="fl">0.530</span>, <span class="fl">0.409</span>, <span class="fl">0.521</span>, <span class="fl">0.478</span>, <span class="fl">0.726</span>, <span class="fl">0.544</span>, <span class="fl">0.588</span>, <span class="fl">0.518</span>, <span class="fl">0.654</span>, <span class="fl">0.662</span>, <span class="fl">0.487</span>, <span class="fl">0.690</span>, <span class="fl">0.608</span>, <span class="fl">0.593</span>],</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sub_diff=7</span><span class="ch">\n</span><span class="st">seed=42'</span>: [<span class="fl">0.736</span>, <span class="fl">0.696</span>, <span class="fl">0.655</span>, <span class="fl">0.662</span>, <span class="fl">0.560</span>, <span class="fl">0.701</span>, <span class="fl">0.718</span>, <span class="fl">0.658</span>, <span class="fl">0.720</span>, <span class="fl">0.574</span>],</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'seed=77</span><span class="ch">\n</span><span class="st">sub_diff=6'</span>: [<span class="fl">0.804</span>, <span class="fl">0.550</span>, <span class="fl">0.869</span>, <span class="fl">0.657</span>, <span class="fl">0.581</span>, <span class="fl">0.670</span>, <span class="fl">0.512</span>, <span class="fl">0.635</span>],</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'seed=77</span><span class="ch">\n</span><span class="st">sub_diff=7'</span>: [<span class="fl">0.764</span>, <span class="fl">0.780</span>, <span class="fl">0.643</span>, <span class="fl">0.812</span>, <span class="fl">0.734</span>, <span class="fl">0.733</span>, <span class="fl">0.782</span>, <span class="fl">0.680</span>, <span class="fl">0.509</span>, <span class="fl">0.675</span>, <span class="fl">0.846</span>],</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'seed=79</span><span class="ch">\n</span><span class="st">sub_diff=8'</span>: [<span class="fl">0.748</span>, <span class="fl">0.822</span>, <span class="fl">0.592</span>, <span class="fl">0.619</span>, <span class="fl">0.851</span>, <span class="fl">0.720</span>, <span class="fl">0.609</span>, <span class="fl">0.634</span>, <span class="fl">0.637</span>],</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'seed=77</span><span class="ch">\n</span><span class="st">sub_diff=8'</span>: [<span class="fl">0.748</span>, <span class="fl">0.661</span>, <span class="fl">0.764</span>, <span class="fl">0.619</span>, <span class="fl">0.704</span>, <span class="fl">0.742</span>, <span class="fl">0.754</span>, <span class="fl">0.509</span>],</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'k_floor=1.5'</span>: [<span class="fl">0.704</span>, <span class="fl">0.674</span>, <span class="fl">0.846</span>, <span class="fl">0.635</span>, <span class="fl">0.512</span>, <span class="fl">0.677</span>, <span class="fl">0.692</span>],</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">5</span>))</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>positions <span class="op">=</span> []</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [<span class="st">'#e74c3c'</span>, <span class="st">'#3498db'</span>, <span class="st">'#2ecc71'</span>, <span class="st">'#f39c12'</span>, <span class="st">'#d35400'</span>, <span class="st">'#e84393'</span>, <span class="st">'#9b59b6'</span>, <span class="st">'#95a5a6'</span>]</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (label, vals) <span class="kw">in</span> <span class="bu">enumerate</span>(strategies.items()):</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.random.normal(i, <span class="fl">0.08</span>, <span class="bu">len</span>(vals))</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    ax.scatter(x, vals, s<span class="op">=</span><span class="dv">40</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, zorder<span class="op">=</span><span class="dv">3</span>, color<span class="op">=</span>colors[i], edgecolors<span class="op">=</span><span class="st">'none'</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    ax.plot([i<span class="op">-</span><span class="fl">0.3</span>, i<span class="op">+</span><span class="fl">0.3</span>], [np.mean(vals), np.mean(vals)], <span class="st">'k-'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, zorder<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    positions.append(i)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(positions)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels(<span class="bu">list</span>(strategies.keys()), fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'raw R²'</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="op">-</span><span class="fl">0.05</span>, <span class="fl">0.95</span>)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>ax.axhline(y<span class="op">=</span><span class="fl">0.869</span>, color<span class="op">=</span><span class="st">'#f39c12'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, label<span class="op">=</span><span class="st">'Peak R² = 0.869'</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>ax.grid(axis<span class="op">=</span><span class="st">'y'</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>ax.legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-strategies" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-strategies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="results_files/figure-html/fig-strategies-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;11: Impact of key strategies on R². Each dot is one iteration. seed=77+sub_diff=6+aug=5500 achieved the global best R²=0.869 (iter 116). Training has extreme intrinsic variance of ±0.2–0.3 R²."><img src="results_files/figure-html/fig-strategies-output-1.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-strategies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Impact of key strategies on R². Each dot is one iteration. seed=77+sub_diff=6+aug=5500 achieved the global best R²=0.869 (iter 116). Training has extreme intrinsic variance of ±0.2–0.3 R².
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="block-4-seed-sensitivity-then-sub_diff7-breakthrough-iter-3748" class="level3">
<h3 class="anchored" data-anchor-id="block-4-seed-sensitivity-then-sub_diff7-breakthrough-iter-3748">Block 4: Seed Sensitivity, then sub_diff=7 Breakthrough (Iter 37–48)</h3>
<p>Block 4 first tested combinations with <code>lr_sub=0.001</code> and revealed seed sensitivity ($$0.2 R²). Then <code>sub_diff=7</code> (stronger monotonicity) achieved a new peak R² = 0.736, lifting the ceiling from 0.73 to 0.74.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10 (iter 37–40)</td>
<td><code>sub_norm=2.0</code>, <code>lr_sub=0.002</code>, <code>lr_node=0.002</code>, L1=0</td>
<td>0.662</td>
<td>All combinations with <code>lr_sub=0.001</code> hurt R² vs baseline</td>
</tr>
<tr class="even">
<td>11 (iter 41–44)</td>
<td>seed=123, <code>aug=4500</code>, <code>sub_diff=3</code>, <code>lr_k=0.007</code></td>
<td>0.690</td>
<td><code>aug=4500</code> most stable (<span class="math inline">\(\alpha = 0.94\)</span>); seed=123 crashed to R²=0.49</td>
</tr>
<tr class="odd">
<td>12 (iter 45–48)</td>
<td><strong><code>sub_diff=7</code></strong>, <code>lr_k=0.004</code>, <code>hidden_dim=128</code>, <code>batch_size=16</code></td>
<td><strong>0.736</strong></td>
<td><code>sub_diff=7</code> new best; wider/deeper MLP and larger batch hurt</td>
</tr>
</tbody>
</table>
<p>Iteration 45 (<code>sub_diff=7</code>, <code>aug=4500</code>) achieved R² = 0.736 with <span class="math inline">\(\alpha = 0.90\)</span> and 15 outliers — the strongest monotonicity constraint within the effective range. Iterations 46–48 confirmed that <code>lr_k=0.004</code> is too slow, <code>hidden_dim_sub=128</code> allows degenerate solutions, and <code>batch_size=16</code> degrades convergence.</p>
</section>
<section id="block-5-confirming-tight-optimization-bounds-iter-4960" class="level3">
<h3 class="anchored" data-anchor-id="block-5-confirming-tight-optimization-bounds-iter-4960">Block 5: Confirming Tight Optimization Bounds (Iter 49–60)</h3>
<p>Block 5 systematically probed the boundaries around the optimal configuration. Every variation hurt R², confirming that the hyperparameter optimum is tightly constrained.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>13 (iter 49–52)</td>
<td><code>aug=5000</code>, <code>sub_diff=8</code>, seed=123, <code>n_layers=4</code></td>
<td>0.696</td>
<td><code>aug=5000</code> hurts (confirmed twice); <code>sub_diff=7</code> improves seed robustness ($$0.08 vs $$0.24)</td>
</tr>
<tr class="even">
<td>14 (iter 53–56)</td>
<td><code>aug=4250</code>, <code>sub_diff=6</code>, seed=123+<code>aug=4000</code>, <code>lr_sub=0.0015</code></td>
<td>0.701</td>
<td>All variations hurt; <code>sub_diff=6</code> too weak, <code>lr_sub=0.0015</code> too high</td>
</tr>
<tr class="odd">
<td>15 (iter 57–60)</td>
<td>seed=123+<code>aug=3500</code>, <strong>seed=99</strong>, L1=0.5, <code>sub_norm=0.5</code></td>
<td><strong>0.718</strong></td>
<td>seed=99 promising (R²=0.72, <span class="math inline">\(\alpha=0.92\)</span>); <code>sub_norm=0.5</code> confirmed essential principle</td>
</tr>
</tbody>
</table>
<p>Tight bounds confirmed: <code>aug=4500</code> (not 4000, 4250, or 5000), <code>sub_diff=7</code> (not 5, 6, or 8), <code>lr_sub=0.001</code> (not 0.0015 or 0.002), <code>lr_k=0.005</code> (not 0.004 or 0.007). <code>sub_diff=7</code> improved seed robustness: the R² gap between seed=42 and seed=123 dropped from 0.24 (with <code>sub_diff=5</code>) to 0.08.</p>
</section>
<section id="block-6-high-variance-discovery-iter-6172" class="level3">
<h3 class="anchored" data-anchor-id="block-6-high-variance-discovery-iter-6172">Block 6: High Variance Discovery (Iter 61–72)</h3>
<p>Block 6 explored new seeds and k_floor variations, then discovered that training has <strong>high intrinsic variance</strong> — an exact replica of the best configuration (iter 45) achieved only R²=0.66 instead of 0.74.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>16 (iter 61–64)</td>
<td>seed=7, seed=99+<code>aug=4250</code>, <code>lr_node=0.0005</code>, <strong><code>k_floor=1.5</code></strong></td>
<td><strong>0.704</strong></td>
<td><code>k_floor=1.5</code> promising (R²=0.70, <span class="math inline">\(\alpha=0.92\)</span>); seed=99 very sensitive to aug</td>
</tr>
<tr class="even">
<td>17 (iter 65–68)</td>
<td><code>k_floor=1.25</code>, <code>k_floor=1.5</code>+seed=99, <code>aug=4750</code>, <code>sub_diff=6</code>+<code>k_floor=1.5</code></td>
<td>0.674</td>
<td><strong>k_floor response is non-monotonic</strong>: 1.25 &lt; 1.0 and 1.5; <code>aug=4750</code> hurts</td>
</tr>
<tr class="odd">
<td>18 (iter 69–72)</td>
<td>Exact replica of iter 45, <code>lr_k=0.0045</code>, <code>hidden_dim_node=32</code>, <code>sub_norm=1.5</code></td>
<td>0.658</td>
<td><strong>HIGH VARIANCE</strong>: replica got R²=0.66 vs original 0.74; MLP<span class="math inline">\(_{\text{sub}}\)</span> c² failure mode</td>
</tr>
</tbody>
</table>
<p>The high variance discovery is significant: identical configurations can produce R² values differing by 0.08, meaning many earlier “improvements” may have been within noise. This makes seed selection and reproducibility central concerns.</p>
</section>
<section id="block-7-seed77-breakthrough-iter-7384" class="level3">
<h3 class="anchored" data-anchor-id="block-7-seed77-breakthrough-iter-7384">Block 7: seed=77 Breakthrough (Iter 73–84)</h3>
<p>Block 7 explored new seeds and found that <strong>seed=77 is a “golden seed”</strong> — achieving R²=0.748 (iter 80) and then R²=0.764 with <code>sub_diff=8</code> (iter 82), surpassing the previous best.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>19 (iter 73–76)</td>
<td>seed=123, <code>lr_sub=0.0012</code>, <code>sub_diff=9</code>, <code>aug=4000</code></td>
<td>0.722</td>
<td>seed=123 improved to R²=0.72 (vs 0.66 earlier); all other variations hurt</td>
</tr>
<tr class="even">
<td>20 (iter 77–80)</td>
<td>seed=7, <code>k_floor=1.5</code>, <code>n_layers=4</code>, <strong>seed=77</strong></td>
<td><strong>0.748</strong></td>
<td><strong>seed=77 new best seed</strong> (R²=0.748, 12 outliers); <code>n_layers=4</code> confirmed harmful</td>
</tr>
<tr class="odd">
<td>21 (iter 81–84)</td>
<td>Replicate seed=77, <strong>seed=77+<code>sub_diff=8</code></strong>, seed=78, <code>aug=5000</code></td>
<td><strong>0.764</strong></td>
<td><strong>seed=77+sub_diff=8 = new global best</strong>; replica got R²=0.66 (variance); seed=78 poor (R²=0.39)</td>
</tr>
</tbody>
</table>
<p>The key finding: <strong>optimal <code>sub_diff</code> is seed-dependent</strong>. <code>sub_diff=8</code> hurts seed=42 (iter 50, R²=0.59) but helps seed=77 (iter 82, R²=0.76). Adjacent seeds (78, 79) do not share seed=77’s properties — “golden seeds” are rare and unpredictable.</p>
</section>
<section id="block-8-seed79-breakthrough-aug5000-iter-8596" class="level3">
<h3 class="anchored" data-anchor-id="block-8-seed79-breakthrough-aug5000-iter-8596">Block 8: seed=79 Breakthrough + aug=5000 (Iter 85–96)</h3>
<p>Block 8 discovered <strong>seed=79 as a new golden seed</strong> (R²=0.748, iter 87) and then broke the R²=0.85 barrier when combined with <code>aug=5000</code> (R²=0.851, iter 96) — refuting the established principle that <code>aug&gt;4500</code> always hurts.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>22 (iter 85–88)</td>
<td>replicate, seed=76, <strong>seed=79</strong>, seed=42+<code>sub_diff=8</code></td>
<td><strong>0.748</strong></td>
<td><strong>seed=79 is a golden seed</strong> (R²=0.75); seed=42+<code>sub_diff=8</code> works with <code>lr_sub=0.001</code> (R²=0.72, refutes earlier principle)</td>
</tr>
<tr class="even">
<td>23 (iter 89–92)</td>
<td><strong>replicate seed=79</strong>, <code>sub_diff=9</code>, seed=80, seed=77+<code>sub_diff=9</code></td>
<td><strong>0.822</strong></td>
<td><strong>seed=79 replicate broke 0.80 barrier</strong> (R²=0.82); <code>sub_diff=9</code> hurts all golden seeds (3× confirmed)</td>
</tr>
<tr class="odd">
<td>24 (iter 93–96)</td>
<td>replicate, <code>sub_diff=7</code>, seed=81, <strong>seed=79+<code>aug=5000</code></strong></td>
<td><strong>0.851</strong></td>
<td><strong>NEW GLOBAL BEST R²=0.851</strong>; <code>aug=5000</code> helps seed=79 (principle refuted for this seed)</td>
</tr>
</tbody>
</table>
<p>The block revealed <strong>extreme training variance</strong> ($$0.2 R²): the same seed=79+<code>sub_diff=8</code> config gave R²=0.82 (iter 89) and R²=0.59 (iter 93). The <code>aug=5000</code> result (iter 96, R²=0.851, 11 outliers, <span class="math inline">\(\alpha\)</span>=0.94, slope=0.99) was the strongest single run at the time.</p>
</section>
<section id="block-9-seed77sub_diff6-discovery-iter-97108" class="level3">
<h3 class="anchored" data-anchor-id="block-9-seed77sub_diff6-discovery-iter-97108">Block 9: seed=77+sub_diff=6 Discovery (Iter 97–108)</h3>
<p>Block 9 explored aug boundaries for golden seeds and discovered that <strong><code>sub_diff=6</code> is optimal for seed=77</strong> — achieving R²=0.804 (iter 106), the second-best result at the time.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>25 (iter 97–100)</td>
<td>replicate seed=79, <code>aug=5500</code>, seed=42+<code>aug=5000</code>, seed=79+<code>sub_diff=7</code></td>
<td>0.742</td>
<td><code>aug=5500</code> hurts seed=79 (R²=0.61); <code>sub_diff=7</code> catastrophic for seed=79 (R²=0.47)</td>
</tr>
<tr class="even">
<td>26 (iter 101–104)</td>
<td>seed=77+<code>aug=4500</code>, replicate seed=79, seed=42+<code>aug=5000</code>, seed=77+<code>sub_diff=7</code></td>
<td><strong>0.764</strong></td>
<td>seed=77 consistent R²≈0.75; seed=79 extreme variance (0.85→0.63)</td>
</tr>
<tr class="odd">
<td>27 (iter 105–108)</td>
<td>replicate, <strong>seed=77+<code>sub_diff=6</code></strong>, seed=42+<code>sub_diff=7</code>, seed=77+<code>sub_diff=9</code></td>
<td><strong>0.804</strong></td>
<td><strong>sub_diff=6 is optimal for seed=77</strong>; <code>sub_diff=9</code> confirmed harmful (3× refuted)</td>
</tr>
</tbody>
</table>
<p>The key insight: optimal <code>sub_diff</code> is not just seed-dependent but follows a pattern — lower values (6) work best for seed=77 while higher values (8) suit seed=79. <code>aug=5500</code> was found to hurt seed=79 but would later prove essential for seed=77.</p>
</section>
<section id="block-10-global-best-r²0.869-iter-109120" class="level3">
<h3 class="anchored" data-anchor-id="block-10-global-best-r²0.869-iter-109120">Block 10: Global Best R²=0.869 (Iter 109–120)</h3>
<p>Block 10 tested <code>sub_diff=6</code> cross-seed transfer and then achieved the <strong>global best R²=0.869</strong> at iteration 116 with seed=77+<code>sub_diff=6</code>+<code>aug=5500</code>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>28 (iter 109–112)</td>
<td>replicate iter 106, seed=77+<code>sub_diff=5</code>, seed=79+<code>sub_diff=6</code>, seed=42+<code>sub_diff=6</code></td>
<td>0.655</td>
<td><strong>Extreme variance</strong>: replica of R²=0.80 got R²=0.55; <code>sub_diff=6</code> doesn’t transfer to seed=79/42</td>
</tr>
<tr class="even">
<td>29 (iter 113–116)</td>
<td>replicate seed=79, seed=77+<code>sub_diff=7</code>+<code>aug=5000</code>, seed=79+<code>sub_diff=7</code>, <strong>seed=77+<code>sub_diff=6</code>+<code>aug=5500</code></strong></td>
<td><strong>0.869</strong></td>
<td><strong>NEW GLOBAL BEST</strong> R²=0.869 (iter 116); aug=5500 helps seed=77 (refutes “aug&gt;4500 hurts”)</td>
</tr>
<tr class="odd">
<td>30 (iter 117–120)</td>
<td>replicate iter 116, <code>aug=5750</code>, <code>sub_diff=5</code>, <code>sub_diff=7</code>+<code>aug=5500</code></td>
<td><strong>0.812</strong></td>
<td><code>aug=5750</code> hurts (R²=0.52); <code>sub_diff=7</code>+<code>aug=5500</code> also strong (R²=0.81)</td>
</tr>
</tbody>
</table>
<p>Iteration 116 (R²=0.869, 10 outliers, <span class="math inline">\(\alpha\)</span>=0.93) established the current global best. The <code>aug=5500</code> finding refuted the principle that longer training always hurts — it is seed-dependent. However, <code>aug=5750</code> overshoots even for seed=77.</p>
</section>
<section id="block-11-robustness-testing-iter-121132" class="level3">
<h3 class="anchored" data-anchor-id="block-11-robustness-testing-iter-121132">Block 11: Robustness Testing (Iter 121–132)</h3>
<p>Block 11 systematically tested robustness of the top configurations and discovered that <strong><code>k_floor=1.5</code> combined with <code>sub_diff=7</code> can achieve R²=0.846</strong> (iter 132, second-best overall).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>31 (iter 121–124)</td>
<td>replicate <code>sub_diff=7</code>, <code>aug=5250</code>, seed=42+<code>sub_diff=7</code>, seed=77+<code>sub_diff=8</code></td>
<td>0.734</td>
<td><code>sub_diff=7</code> more robust than <code>sub_diff=6</code> (variance ~0.08 vs ~0.21); <code>sub_diff=8</code> hurts seed=77</td>
</tr>
<tr class="even">
<td>32 (iter 125–128)</td>
<td>replicate, <code>aug=5750</code>, seed=79+<code>sub_diff=7</code>, seed=77+<code>sub_diff=6</code></td>
<td><strong>0.782</strong></td>
<td><code>aug=5750</code> hurts <code>sub_diff=7</code> too; <code>sub_diff=7</code> doesn’t transfer to seed=79</td>
</tr>
<tr class="odd">
<td>33 (iter 129–132)</td>
<td>worst replicate, <code>aug=5250</code>, seed=42+<code>sub_diff=6</code>, <strong>seed=77+<code>sub_diff=7</code>+<code>k_floor=1.5</code></strong></td>
<td><strong>0.846</strong></td>
<td><strong>2ND BEST R²=0.846</strong> with <code>k_floor=1.5</code>; extreme variance persists (R²=0.51–0.85)</td>
</tr>
</tbody>
</table>
<p>The <code>sub_diff=7</code> configuration proved more robust than <code>sub_diff=6</code> for seed=77: R² range 0.73–0.81 (variance ~0.08) vs 0.55–0.87 (variance ~0.21). The trade-off is clear — <code>sub_diff=6</code> has a higher ceiling but lower floor.</p>
</section>
<section id="block-12-k_floor1.5-variance-confirmed-iter-133136" class="level3">
<h3 class="anchored" data-anchor-id="block-12-k_floor1.5-variance-confirmed-iter-133136">Block 12: k_floor=1.5 Variance Confirmed (Iter 133–136)</h3>
<p>Block 12 tested whether <code>k_floor=1.5</code> reliably improves R² and found that <strong>variance dominates configuration differences</strong>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 34%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Batch</th>
<th>Key mutation</th>
<th>Best R²</th>
<th>Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>34 (iter 133–136)</td>
<td>replicate iter 132, <code>sub_diff=6</code>+<code>k_floor=1.5</code>, seed=42+<code>k_floor=1.5</code>, <code>k_floor=2.0</code></td>
<td>0.692</td>
<td>Replicate R²=0.64 vs 0.85 (variance ~0.21); <code>sub_diff=6</code> requires <code>k_floor=1.0</code>; <code>k_floor=2.0</code> not catastrophic</td>
</tr>
</tbody>
</table>
<p>The main conclusion: with $$0.2–0.3 R² training variance, <strong>configuration differences below ~0.15 R² are indistinguishable from noise</strong>.</p>
</section>
<section id="ucb-exploration-tree" class="level3">
<h3 class="anchored" data-anchor-id="ucb-exploration-tree">UCB Exploration Tree</h3>
<div id="fig-ucb-tree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ucb-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/ucb_tree.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;12: UCB tree after 24 iterations (snapshot). Each node represents a hyperparameter configuration; color encodes R² (green = high, red = low). The tree shows how the exploration branched from the k_floor=1.0 breakthrough (node 14) and converged on the aug=4000 regime. The tree has since grown to 136 nodes; the overall best is node 116 (R² = 0.869)."><img src="figures/rank_50/ucb_tree.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ucb-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: UCB tree after 24 iterations (snapshot). Each node represents a hyperparameter configuration; color encodes R² (green = high, red = low). The tree shows how the exploration branched from the <code>k_floor=1.0</code> breakthrough (node 14) and converged on the <code>aug=4000</code> regime. The tree has since grown to 136 nodes; the overall best is node 116 (R² = 0.869).
</figcaption>
</figure>
</div>
</section>
<section id="established-principles" class="level3">
<h3 class="anchored" data-anchor-id="established-principles">Established Principles</h3>
<p>The LLM’s persistent memory has accumulated these validated principles after 136 iterations:</p>
<ol type="1">
<li><strong><code>coeff_MLP_sub_norm=1.0</code> is essential</strong> — enables correct MLP shapes: c² becomes quadratic, MLP<span class="math inline">\(_{\text{node}}\)</span> activates. <code>sub_norm=0.5</code> and <code>sub_norm=1.5</code> both hurt (iter 60, 72).</li>
<li><strong><code>coeff_k_floor=1.0</code>–<code>1.5</code> is the optimal range</strong> — R² jumped from 0.06 to 0.51 (10× improvement) with <code>k_floor=1.0</code>. <code>k_floor=1.5</code>+<code>sub_diff=7</code> achieved R²=0.85 (iter 132, 2nd best). Response is <strong>non-monotonic</strong>: <code>k_floor=1.25</code> &lt; both 1.0 and 1.5 (iter 65). <code>k_floor</code> response is <code>sub_diff</code>-dependent: <code>sub_diff=6</code> requires <code>k_floor=1.0</code> (iter 134).</li>
<li><strong>Optimal <code>aug</code> is seed-dependent</strong> — <code>aug=5500</code> is optimal for seed=77 (R²=0.87, iter 116), <code>aug=5000</code> for seed=79 (R²=0.85, iter 96), <code>aug=4500</code> for seed=42. <code>aug=5750</code> hurts all configs (iter 118, 126). <code>aug=5500</code> is the hard ceiling.</li>
<li><strong><code>lr_k=0.005</code> is optimal</strong> — lower (0.003, 0.004, 0.0045) too slow, higher (0.007, 0.01) destabilizes (confirmed across 6 iterations)</li>
<li><strong><code>lr_sub=0.001</code> is optimal</strong> — 2× increase from 0.0005 broke the R² plateau; <code>lr_sub=0.002</code> too high (iter 38); <code>lr_sub=0.0015</code> hurts (iter 56); <code>lr_sub=0.0012</code> hurts (iter 74)</li>
<li><strong><code>lr_node=0.001</code> is optimal</strong> — <code>lr_node=0.005</code> destabilizes (iter 11); <code>lr_node=0.0005</code> hurts (iter 63)</li>
<li><strong>Optimal <code>sub_diff</code> is seed-specific</strong> — <code>sub_diff=6</code> for seed=77 (R²=0.87, iter 116), <code>sub_diff=7</code> for seed=42 (R²=0.74, iter 45), <code>sub_diff=8</code> for seed=79 (R²=0.85, iter 96). <code>sub_diff=9</code> hurts all golden seeds (3× confirmed). <code>sub_diff=5</code> underperforms (iter 119).</li>
<li>**Training has extreme intrinsic variance ($<span class="math inline">\(0.2--0.3 R²)** — exact replicas: iter 132 R²=0.85 vs iter 133 R²=0.64 (\)</span><span class="math inline">\(=0.21); iter 106 R²=0.80 vs iter 109 R²=0.55 (\)</span>$=0.25). Configuration differences below ~0.15 R² are indistinguishable from noise.</li>
<li><strong>seed=77 is the best seed</strong> — R²=0.869 with <code>sub_diff=6</code>+<code>aug=5500</code> (iter 116, global best). <code>sub_diff=7</code> more robust (variance ~0.08) but lower ceiling. seed=79 second best (R²=0.851, iter 96) but higher variance. Adjacent seeds (76, 78, 80, 81) are poor — “golden seeds” are rare.</li>
<li><strong><code>batch_size=8</code> is optimal</strong> — <code>batch_size=16</code> hurts R² (iter 48)</li>
<li><strong>Default MLP architecture is optimal</strong> — <code>hidden_dim_sub=128</code> allows degenerate solutions (iter 47); <code>hidden_dim_node=32</code> significantly worse (iter 71); <code>n_layers_sub=4</code> hurts (iter 52, 79)</li>
<li><strong><code>coeff_MLP_node_L1=1.0</code> is optimal</strong> — L1=0.0 + long training harmful (iter 22, 29, 40); L1=0.5 hurts (iter 59)</li>
<li><strong><code>sub_diff=7</code> is the most robust setting</strong> — variance ~0.08 R² for seed=77 (range 0.73–0.81) vs <code>sub_diff=6</code>’s ~0.21 (range 0.55–0.87). Does not transfer well to seed=42 or seed=79.</li>
<li><strong>MLP<span class="math inline">\(_{\text{node}}\)</span> remains flat across all 136 iterations</strong> — homeostasis <span class="math inline">\(-\lambda(c - c^{\text{base}})\)</span> is never learned, regardless of configuration</li>
</ol>
</section>
<section id="refuted-hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="refuted-hypotheses">Refuted Hypotheses</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 55%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Hypothesis</th>
<th>Evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Recurrent training breaks degeneracy</td>
<td>No R² improvement, 3.5× slower (iter 13, 34)</td>
</tr>
<tr class="even">
<td>Smaller MLP improves k recovery</td>
<td>Worst R² = 0.011 (iter 15)</td>
</tr>
<tr class="odd">
<td>Higher <code>lr_node</code> activates MLP<span class="math inline">\(_{\text{node}}\)</span></td>
<td><code>lr_node=0.005</code> hurts (iter 11); 0.002 no effect (iter 26, 39)</td>
</tr>
<tr class="even">
<td>Different seed breaks degeneracy</td>
<td>Same MLP<span class="math inline">\(_{\text{node}}\)</span> flatness (iter 27); R² variance $$0.2 (iter 41)</td>
</tr>
<tr class="odd">
<td>Stronger monotonicity (<code>sub_diff=10</code>) helps</td>
<td>R² dropped to 0.41 (iter 32)</td>
</tr>
<tr class="even">
<td>Weaker monotonicity (<code>sub_diff=3</code>) helps</td>
<td>R² dropped to 0.61 (iter 43)</td>
</tr>
<tr class="odd">
<td>Smaller batch size helps convergence</td>
<td>R² dropped (iter 28)</td>
</tr>
<tr class="even">
<td><code>aug=5000</code> continues to improve</td>
<td>Confirmed 3×: iter 25 (0.65), iter 49 (0.70), iter 84 (0.69)</td>
</tr>
<tr class="odd">
<td><code>lr_sub=0.002</code> improves over 0.001</td>
<td>R² dropped from 0.73 to 0.52 (iter 38)</td>
</tr>
<tr class="even">
<td><code>sub_norm=2.0</code> improves R²</td>
<td>Improves <span class="math inline">\(\alpha\)</span> but hurts R² (iter 30, 37)</td>
</tr>
<tr class="odd">
<td>Combining <code>lr_sub=0.001</code> with other changes</td>
<td>All combinations hurt R² vs baseline (iter 37–40)</td>
</tr>
<tr class="even">
<td>Wider MLP<span class="math inline">\(_{\text{sub}}\)</span> (<code>hidden_dim=128</code>) helps</td>
<td>R² dropped to 0.56 — allows degenerate solutions (iter 47)</td>
</tr>
<tr class="odd">
<td>Larger <code>batch_size=16</code> stabilizes gradients</td>
<td>R² dropped to 0.56 (iter 48)</td>
</tr>
<tr class="even">
<td><code>sub_diff=8</code> hurts all seeds</td>
<td>Hurts seed=42 (iter 50, R²=0.59) but helps seed=77 (iter 82, R²=0.76)</td>
</tr>
<tr class="odd">
<td><code>sub_diff=6</code> is better than 7</td>
<td>R² dropped from 0.74 to 0.56 (iter 54)</td>
</tr>
<tr class="even">
<td>Deeper MLP<span class="math inline">\(_{\text{sub}}\)</span> (<code>n_layers=4</code>) helps</td>
<td>R² dropped to 0.55 (iter 52); confirmed iter 79 (R²=0.47)</td>
</tr>
<tr class="odd">
<td><code>lr_sub=0.0015</code> (intermediate) helps</td>
<td>R² dropped from 0.74 to 0.60 (iter 56)</td>
</tr>
<tr class="even">
<td><code>lr_k=0.004</code> gives finer convergence</td>
<td>R² dropped to 0.48 — too slow (iter 46)</td>
</tr>
<tr class="odd">
<td><code>sub_norm=0.5</code> helps</td>
<td>R² dropped from 0.74 to 0.60 (iter 60)</td>
</tr>
<tr class="even">
<td>Intermediate <code>k_floor=1.25</code> is optimal</td>
<td>R²=0.56, worse than both 1.0 and 1.5 — non-monotonic (iter 65)</td>
</tr>
<tr class="odd">
<td><code>aug=4750</code> within safe range</td>
<td>R² dropped to 0.66 despite <span class="math inline">\(\alpha\)</span>=0.96 (iter 67)</td>
</tr>
<tr class="even">
<td><code>sub_norm=1.5</code> better than 1.0</td>
<td>R²=0.55 vs 0.66 (iter 72)</td>
</tr>
<tr class="odd">
<td><code>hidden_dim_node=32</code> simpler is better</td>
<td>R²=0.47, significantly worse (iter 71)</td>
</tr>
<tr class="even">
<td><code>lr_sub=0.0012</code> helps MLP<span class="math inline">\(_{\text{sub}}\)</span></td>
<td>R²=0.58 vs 0.66 (iter 74)</td>
</tr>
<tr class="odd">
<td>seed=42 is the best seed</td>
<td>seed=79 achieved R²=0.851 (iter 96), seed=77 R²=0.764 (iter 82)</td>
</tr>
<tr class="even">
<td>Adjacent seeds share properties</td>
<td>seed=76 R²=0.51 (iter 86), seed=78 R²=0.39 (iter 83), seed=80 R²=0.57 (iter 91), seed=81 R²=0.55 (iter 95) — all poor</td>
</tr>
<tr class="odd">
<td><code>k_floor=1.5</code> is reproducible</td>
<td>Same config gave R²=0.70 (iter 64) and R²=0.51 (iter 78)</td>
</tr>
<tr class="even">
<td><code>sub_diff=8</code> hurts seed=42</td>
<td>Refuted: iter 88 got R²=0.72 with seed=42+<code>sub_diff=8</code> (key: <code>lr_sub=0.001</code> not 0.0005)</td>
</tr>
<tr class="odd">
<td><code>sub_diff=9</code> forces c² quadratic</td>
<td>Hurt all golden seeds: seed=79 0.75→0.64 (iter 90), seed=77 0.76→0.70 (iter 92), 3× confirmed</td>
</tr>
<tr class="even">
<td><code>aug=5000</code> always hurts R²</td>
<td>Refuted for seed=79: R²=0.851 with <code>aug=5000</code> (iter 96); then <code>aug=5500</code> helps seed=77 to R²=0.869 (iter 116)</td>
</tr>
<tr class="odd">
<td><code>aug=5500</code> hurts all seeds</td>
<td>Refuted: seed=77+<code>sub_diff=6</code>+<code>aug=5500</code> gave R²=0.869 (iter 116, global best)</td>
</tr>
<tr class="even">
<td><code>sub_diff=6</code> transfers across seeds</td>
<td><code>sub_diff=6</code> doesn’t help seed=79 (R²=0.65, iter 111) or seed=42 (R²=0.59, iter 112)</td>
</tr>
<tr class="odd">
<td><code>sub_diff=7</code> transfers to all seeds</td>
<td>seed=42 R²=0.57 (iter 123), seed=79 R²=0.54 (iter 127)</td>
</tr>
<tr class="even">
<td><code>sub_diff=8</code> works for seed=77</td>
<td>R²=0.51 (iter 124) vs <code>sub_diff=6</code> R²=0.87 and <code>sub_diff=7</code> R²=0.81</td>
</tr>
<tr class="odd">
<td><code>aug=5750</code> tolerates any <code>sub_diff</code></td>
<td>Hurts both <code>sub_diff=6</code> (iter 118, R²=0.52) and <code>sub_diff=7</code> (iter 126, R²=0.68)</td>
</tr>
<tr class="even">
<td><code>k_floor=1.5</code> reduces variance</td>
<td>Same config: iter 132 R²=0.85 vs iter 133 R²=0.64 (variance ~0.21 persists)</td>
</tr>
<tr class="odd">
<td><code>k_floor=1.5</code> helps <code>sub_diff=6</code></td>
<td>R²=0.51 (iter 134) vs <code>k_floor=1.0</code> R²=0.87 (iter 116)</td>
</tr>
<tr class="even">
<td><code>k_floor=2.0</code> is catastrophically worse</td>
<td>R²=0.69 (iter 136), within variance range of <code>k_floor=1.5</code></td>
</tr>
</tbody>
</table>
</section>
<section id="open-questions" class="level3">
<h3 class="anchored" data-anchor-id="open-questions">Open Questions</h3>
<ol type="1">
<li><strong>Is R² <span class="math inline">\(\geq\)</span> 0.90 achievable?</strong> After 136 iterations, the best R²=0.869 (seed=77+sub_diff=6+aug=5500). Training variance of $$0.2–0.3 means a lucky run could reach 0.90+, but systematic improvement requires reducing variance.</li>
<li><strong>Can variance be reduced?</strong> The dominant bottleneck is now stochastic variance ($$0.2–0.3 R²), not hyperparameter tuning. Ensemble averaging, longer training with learning rate scheduling, or gradient accumulation could help.</li>
<li><strong>Are there more “golden seeds”?</strong> Only seeds 77, 79, and 42 are confirmed productive. Adjacent seeds (76, 78, 80, 81) are all poor. What makes a seed “golden” remains unknown.</li>
<li><strong>Why is the k_floor response non-monotonic?</strong> <code>k_floor=1.25</code> is worse than both 1.0 and 1.5 (iter 65). The mechanism is unknown.</li>
<li><strong>Is the remaining 13% error from identifiability issues?</strong> Multiple <span class="math inline">\(k\)</span> combinations may produce similar <span class="math inline">\(dc/dt\)</span>, setting a fundamental ceiling on single-run recovery.</li>
</ol>
</section>
</section>
<section id="why-homeostasis-is-not-learned" class="level2">
<h2 class="anchored" data-anchor-id="why-homeostasis-is-not-learned">Why Homeostasis Is Not Learned</h2>
<p>Across all 136 iterations, MLP<span class="math inline">\(_{\text{node}}\)</span> remains flat — the homeostasis function <span class="math inline">\(-\lambda_t(c_i - c_i^{\text{baseline}})\)</span> is never recovered. This is not a hyperparameter issue. It is a structural limitation of single-step (<span class="math inline">\(t \to t+1\)</span>) training.</p>
<section id="the-scale-mismatch-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-scale-mismatch-problem">The scale mismatch problem</h3>
<p>The GNN predicts <span class="math inline">\(dc/dt\)</span> at each time step:</p>
<p><span class="math display">\[
\frac{dc_i}{dt} = \underbrace{\text{MLP}_{\text{node}}(c_i, a_i)}_{\text{homeostasis}} + \underbrace{\sum_j S_{ij} \cdot k_j \prod_k \text{MLP}_{\text{sub}}(c_k, |S_{kj}|)}_{\text{reaction}}
\]</span></p>
<p>The reaction term dominates the instantaneous <span class="math inline">\(dc/dt\)</span> — it drives the fast oscillatory dynamics. Homeostasis acts as a slow restoring force that only manifests over many time steps: it prevents concentrations from drifting away from baseline. In a single-step loss <span class="math inline">\(\| \hat{y}_{t+1} - y_{t+1} \|^2\)</span>, the gradient signal from homeostasis is negligible compared to the reaction term. The optimizer has no reason to learn it.</p>
</section>
<section id="homeostasis-is-an-integral-problem" class="level3">
<h3 class="anchored" data-anchor-id="homeostasis-is-an-integral-problem">Homeostasis is an integral problem</h3>
<p>Homeostasis determines the <strong>long-term trajectory envelope</strong>, not the instantaneous derivative. Its effect accumulates over time:</p>
<p><span class="math display">\[
c_i(t + T) \approx c_i(t) + \int_t^{t+T} \left[ -\lambda_i (c_i - c_i^{\text{base}}) + \text{reaction terms} \right] d\tau
\]</span></p>
<p>A model trained on <span class="math inline">\(t \to t+1\)</span> can achieve low loss by fitting the dominant reaction signal and ignoring the small homeostatic correction. Over many steps this error accumulates — but the single-step loss never sees it.</p>
</section>
<section id="proposed-approach-two-phase-training" class="level3">
<h3 class="anchored" data-anchor-id="proposed-approach-two-phase-training">Proposed approach: two-phase training</h3>
<p>To recover homeostasis, we propose a two-phase training scheme:</p>
<ol type="1">
<li><p><strong>Phase 1 — Reaction recovery</strong> (<span class="math inline">\(t \to t+1\)</span>): Train as currently done. Recover <span class="math inline">\(k_j\)</span>, MLP<span class="math inline">\(_{\text{sub}}\)</span>, and the stoichiometric structure. Freeze these parameters.</p></li>
<li><p><strong>Phase 2 — Homeostasis recovery</strong> (recurrent, <span class="math inline">\(t \to t+T\)</span>): With the reaction term frozen, train only MLP<span class="math inline">\(_{\text{node}}\)</span> and embeddings <span class="math inline">\(a_i\)</span> using multi-step rollout. The recurrent loss forces the model to match trajectories over <span class="math inline">\(T\)</span> steps, where the homeostatic drift becomes visible.</p></li>
</ol>
<p>This separates the two learning problems by time scale: fast reactions are learned from instantaneous gradients, slow homeostasis from trajectory matching. The key insight is that recurrent training is not needed for <span class="math inline">\(k_j\)</span> recovery (it was tried and failed — iter 13, 34), but may be essential specifically for homeostasis once the reaction parameters are frozen.</p>
</section>
<section id="alternative-approach-residual-based-supervision" class="level3">
<h3 class="anchored" data-anchor-id="alternative-approach-residual-based-supervision">Alternative approach: residual-based supervision</h3>
<p>The kinograph residual (<a href="#fig-kinograph-best" class="quarto-xref">Figure&nbsp;8</a>, bottom-left) directly reveals what the single-step model cannot learn. After Phase 1, we can roll out the learned model autoregressively:</p>
<p><span class="math display">\[
\hat{c}_i(t+1) = \hat{c}_i(t) + \Delta t \cdot \left[ \sum_j S_{ij} \cdot k_j \prod_k \text{MLP}_{\text{sub}}(\hat{c}_k, |S_{kj}|) \right]
\]</span></p>
<p>The rollout trajectory <span class="math inline">\(\hat{c}(t)\)</span> drifts from the observation <span class="math inline">\(c(t)\)</span> because the missing homeostatic restoring force is not applied at each step. The accumulated residual</p>
<p><span class="math display">\[
r_i(t) = c_i(t) - \hat{c}_i(t)
\]</span></p>
<p>is precisely the integrated effect of the missing slow terms — homeostasis, external sources, and degradation. This residual provides a direct supervision signal for Phase 2 without requiring backpropagation through time: we can compute a per-step target</p>
<p><span class="math display">\[
\frac{r_i(t+1) - r_i(t)}{\Delta t} \approx \text{MLP}_{\text{node}}(c_i(t), a_i)
\]</span></p>
<p>and train MLP<span class="math inline">\(_{\text{node}}\)</span> with a standard single-step loss on this derived target. This avoids the instabilities of recurrent training while still capturing the long-term dynamics that the reaction-only model structurally cannot predict.</p>
</section>
<section id="direct-evidence-the-one-step-derivative-residual-is-the-homeostasis-signal" class="level3">
<h3 class="anchored" data-anchor-id="direct-evidence-the-one-step-derivative-residual-is-the-homeostasis-signal">Direct evidence: the one-step derivative residual is the homeostasis signal</h3>
<p>The one-step derivative diagnostic feeds the <strong>true concentration</strong> at each timestep and records the GNN’s predicted <span class="math inline">\(dc/dt\)</span>. Since MLP<span class="math inline">\(_{\text{node}} \approx 0\)</span> across all 136 iterations, the prediction is purely the reaction term:</p>
<p><span class="math display">\[
\widehat{\frac{dc_i}{dt}} = \underbrace{0}_{\text{MLP}_{\text{node}}} + \sum_j S_{ij} \cdot k_j \prod_k \text{MLP}_{\text{sub}}(c_k, |S_{kj}|)
\]</span></p>
<p>The residual between prediction and ground truth is therefore:</p>
<p><span class="math display">\[
\widehat{\frac{dc_i}{dt}} - \frac{dc_i}{dt} = -\text{MLP}_{\text{node}}^{\text{true}}(c_i, a_i) = \lambda_i(c_i - c_i^{\text{base}})
\]</span></p>
<p>This is the <strong>negative of the unlearned homeostasis term</strong>, directly observable per metabolite over time.</p>
<div id="fig-deriv-residual-traces" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-deriv-residual-traces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/rank_50/deriv_residual_traces.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figure&nbsp;13: One-step derivative residual traces (Iteration 96, best model). Each trace shows \widehat{dc/dt} - dc/dt for a single metabolite — the signal that single-step training structurally cannot capture. The smooth, slow-varying shape is consistent with homeostatic regulation \lambda(c - c^{\text{base}}). Metabolites with the highest MAE (36, 99, 10) correspond to the strongest homeostatic restoring forces, not GNN prediction errors."><img src="figures/rank_50/deriv_residual_traces.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-deriv-residual-traces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: One-step derivative residual traces (Iteration 96, best model). Each trace shows <span class="math inline">\(\widehat{dc/dt} - dc/dt\)</span> for a single metabolite — the signal that single-step training structurally cannot capture. The smooth, slow-varying shape is consistent with homeostatic regulation <span class="math inline">\(\lambda(c - c^{\text{base}})\)</span>. Metabolites with the highest MAE (36, 99, 10) correspond to the strongest homeostatic restoring forces, not GNN prediction errors.
</figcaption>
</figure>
</div>
<p>The derivative residual traces confirm three properties expected of the homeostasis signal:</p>
<ol type="1">
<li><strong>Smooth and slow-varying</strong> — the traces lack the fast oscillatory structure of the reaction term, consistent with a restoring force that operates on longer timescales.</li>
<li><strong>Non-zero mean per metabolite</strong> — each metabolite has a persistent bias, reflecting the time-averaged homeostatic drive <span class="math inline">\(\lambda_i(c_i - c_i^{\text{base}})\)</span>.</li>
<li><strong>Metabolite-specific amplitude</strong> — the MAE varies by metabolite (0.02 to 0.14), suggesting heterogeneous homeostatic strength <span class="math inline">\(\lambda_i\)</span> across the network.</li>
</ol>
<p>These residual traces provide a ready-made supervision signal for Phase 2: rather than requiring backpropagation through time, MLP<span class="math inline">\(_{\text{node}}\)</span> can be trained directly on <span class="math inline">\(-(\widehat{dc/dt} - dc/dt)\)</span> at each timestep, using the frozen Phase 1 reaction model.</p>
<p>This approach is an instance of the <strong>Universal Differential Equations</strong> framework (<a href="https://arxiv.org/abs/2001.04385">Rackauckas et al., 2021</a>), where a partially known ODE is augmented with a neural network that learns the missing terms from data. Here, the known part is the reaction dynamics <span class="math inline">\(\sum_j S_{ij} k_j \prod_k \text{MLP}_{\text{sub}}\)</span>, and the unknown part is the homeostatic correction learned by MLP<span class="math inline">\(_{\text{node}}\)</span>. The residual-based supervision strategy is also related to <strong>PDE-Refiner</strong> (<a href="https://arxiv.org/abs/2308.05732">Lippe et al., NeurIPS 2023</a>), which uses iterative refinement on rollout residuals to recover low-amplitude dynamics that single-pass neural solvers miss — analogous to the small homeostatic signal masked by dominant reactions.</p>
</section>
<section id="related-work" class="level3">
<h3 class="anchored" data-anchor-id="related-work">Related work</h3>
<p>The difficulty of learning slow dynamics from single-step training is well established in the literature:</p>
<ul>
<li><p><strong>Teacher forcing and long-term dependencies.</strong> <a href="https://direct.mit.edu/neco/article/1/2/270/5490/">Williams &amp; Zipser (1989)</a> introduced teacher forcing for RNNs: feeding ground-truth inputs at each step. <a href="https://ieeexplore.ieee.org/document/279181">Bengio et al.&nbsp;(1994)</a> showed that gradient-based learning of long-term dependencies is fundamentally difficult because short-term gradient contributions dominate, exactly the mechanism that prevents our GNN from learning homeostasis.</p></li>
<li><p><strong>Scheduled sampling.</strong> <a href="https://arxiv.org/abs/1506.03099">Bengio et al.&nbsp;(2015)</a> proposed a curriculum strategy that gradually transitions from teacher forcing (single-step) to free-running (multi-step) prediction, reducing the train–inference discrepancy. Our two-phase proposal is conceptually related: Phase 1 is teacher-forced, Phase 2 uses multi-step rollout.</p></li>
<li><p><strong>Multiple shooting for Neural ODEs.</strong> <a href="https://arxiv.org/abs/2106.03885">Massaroli et al.&nbsp;(2021)</a> introduced differentiable multiple shooting layers that parallelize trajectory integration. <a href="https://arxiv.org/abs/2109.06786">Turan &amp; Jäschke (2021)</a> showed that standard Neural ODE fitting on oscillatory data produces “flattened” trajectories — multiple shooting recovers the true dynamics by breaking long horizons into segments. This directly addresses the failure mode we observe.</p></li>
<li><p><strong>Stiff Neural ODEs.</strong> <a href="https://arxiv.org/abs/2103.15341">Kim et al.&nbsp;(2021)</a> showed that learning neural ODEs for systems with widely separated time scales (stiff systems) requires proper output scaling and stabilized gradients — the fast dynamics otherwise dominate training, exactly as in our reaction-vs-homeostasis scale mismatch.</p></li>
<li><p><strong>Multi-scale separation in dynamical systems.</strong> <a href="https://doi.org/10.1016/0022-0396(79)90152-9">Fenichel (1979)</a> established geometric singular perturbation theory: for systems with fast and slow time scales, the fast subsystem is solved first, then the dynamics are reduced to a slow manifold. Our two-phase training mirrors this decomposition — Phase 1 recovers the fast reaction dynamics, Phase 2 learns the slow homeostatic manifold.</p></li>
<li><p><strong>Latent timescales in Neural ODEs.</strong> <a href="https://arxiv.org/abs/2403.02224">Gupta et al.&nbsp;(2024)</a> showed that training trajectory length directly controls the timescales a Neural ODE can recover: longer trajectories are needed to capture slower dynamics. This supports the need for multi-step rollout in Phase 2.</p></li>
</ul>
<p>The scale mismatch / integral argument is essentially the same observation that Bengio (1994) made for RNNs and Kim et al.&nbsp;(2021) made for stiff ODEs. The two-phase proposal mirrors Fenichel’s fast-then-slow decomposition. The novelty here is applying this reasoning to GNN-based metabolic network recovery, where the bipartite graph structure and the identifiability of rate constants <span class="math inline">\(k_j\)</span> add domain-specific constraints.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/allierc\.github\.io\/MetabolismGraph\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Cédric Allier · <span style="color: #999; font-size: 0.85em;">Generated with <a href="https://claude.ai" style="color: #999;">Claude</a> · Reviewed by Cédric Allier</span></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>